version: '3.7'

services:
  web:
    environment:
      - example=hello
    build: .
    ports:
      - 3400:5000
    volumes:
      # map a location on the lambda server to the docker container
      # lambda_server_path:docker_container_path
      - .:/app
        #- /home/usertest/bigdata/flask_web:/bigdata
      # bind mount (starts with . or /)
      - volume_name:/bigdata
      # named volume (doesn't start with . or /)


volumes:
  volume_name:
